{noup} mfd: fix typo in function definition that causes build failures
Fixes:

In file included from ../drivers/net/ethernet/ti/cpsw-common.c:18:0:
../include/linux/mfd/syscon.h:56:1: error: expected identifier or '(' before '{' token
In file included from ../drivers/net/ethernet/ti/cpsw-common.c:18:0:
../include/linux/mfd/syscon.h:54:101: warning: 'syscon_regmap_lookup_by_dev_property' declared 'static' but never defined [-Wunused-function]
make[5]: *** [drivers/net/ethernet/ti/cpsw-common.o] Error 1
In file included from ../drivers/net/ethernet/ti/davinci_emac.c:69:0:
../include/linux/mfd/syscon.h:56:1: error: expected identifier or '(' before '{' token
../include/linux/mfd/syscon.h:54:101: warning: 'syscon_regmap_lookup_by_dev_property' declared 'static' but never defined [-Wunused-function]
make[5]: *** [drivers/net/ethernet/ti/davinci_emac.o] Error 1

Signed-off-by: Amit Kucheria <amit.kucheria@linaro.org>