{topost} ACPI: IORT: fix the compile error on x86
When compiled on x86, error shows:
drivers/built-in.o: In function `pci_msi_domain_get_msi_rid':
(.text+0x1cd61): undefined reference to `iort_find_pci_id'
make: *** [vmlinux] Error 1

iort.c will only complied on ARM64 as we select CONFIG_IORT_TABLE
on ARM64, so we need to introduce the stub function of
iort_find_pci_id() when CONFIG_IORT_TABLE=n, not CONFIG_ACPI.

Signed-off-by: Hanjun Guo <hanjun.guo@linaro.org>